import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import Header from '@/layout/header/Header'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="flex justify-center bg-green">
        <div className="bg-gradient-to-r from-cyan-500 to-blue-500">1</div>
        <div className={styles.red}>2</div>
        <div className={styles.red}>3</div>
      </main>
    </>
  )
}
